version: '3.7'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ias
    ports:
      - '5555:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./resources/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
    postgres-data: